export const Constants = {
  UPLOAD_IMAGE : "UPLOAD_IMAGE",
  CREATE_ANNOTATION : "CREATE_ANNOTATION",
  UPLOAD_IMAGE_SUCESS : "UPLOAD_IMAGE_SUCESS",
  CREATE_ANNOTATION_SUCESS : "CREATE_ANNOTATION_SUCESS",
  SAVE_SELECTED_IMG_ID : "SAVE_SELECTED_IMG_ID"
};
